import React, { useEffect, useState } from "react";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import Banner from "../components/banner";
import CoffeeCards from "../components/coffeecards";

import { fetchCoffeeStores } from "../lib/coffee_store";

import trackGeoLocation from "../hooks/trackGeoLocation";

export async function getStaticProps(context) {
  const storeData = await fetchCoffeeStores();
  return {
    props: {
      Stores: storeData,
    },
  };
}

export default function Home(props) {
  const { latLng, trackLocation, locationErrorMsg, findingLocation } =
    trackGeoLocation();
  console.log(latLng);
  const { Stores } = props; // Stores which we are pre-rendering
  const [storesByLocation, setStoresByLocation] = useState("");

  useEffect(async () => {
    if (latLng) {
      const storesByLocation = await fetchCoffeeStores(latLng);
      console.log({ storesByLocation });
      setStoresByLocation(storesByLocation);
    }
  }, [latLng]);

  return (
    <div className={styles.container}>
      <Head>
        <title>GPS Coffee</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Banner
        buttonText={findingLocation ? "Loading..." : "Locate your coffee"}
        id="0"
        clickHandler={trackLocation}
      />
      {locationErrorMsg && <p>Something went wrong: {locationErrorMsg}</p>}
      {storesByLocation && (
        <div>
          <h1>Coffee Stores Near you </h1>
          <CoffeeCards Stores={Stores} />
        </div>
      )}
      <div>
        <h1>Coffee Stores </h1>
        <CoffeeCards Stores={Stores} />
      </div>
    </div>
  );
}
