import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Banner from '../components/banner'
import CoffeeCards from '../components/coffeecards'
import Stores from "../public/coffee-stores.json";
import {fetchCoffeeStores} from "../lib/coffee_store";

export async function getStaticProps(context)  {
  const storeData = await fetchCoffeeStores();
  return {
      props: {
          Stores: storeData
      }
  }
}


export default function Home(props) {
  const {Stores } = props;
  return (
    <div className={styles.container}>
      <Head>
        <title>GPS Coffee</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Banner buttonText={"Locate your coffee"} id="0" />

      <CoffeeCards Stores={Stores}/>
    </div>
  )
}
