import Head from 'next/head'

import styles from '../styles/Home.module.css'
import Banner from '../components/banner'
import CoffeeCards from '../components/coffeecards'

import {fetchCoffeeStores} from "../lib/coffee_store";

import trackGeoLocation from "../hooks/trackGeoLocation";


export async function getStaticProps(context)  {
  const storeData = await fetchCoffeeStores();
  return {
      props: {
          Stores: storeData
      }
  }
}


export default function Home(props) {
  const {latLng, trackLocation, locationErrorMsg, findingLocation} = trackGeoLocation();
  
  const {Stores } = props;

  return (
    <div className={styles.container}>
      <Head>
        <title>GPS Coffee</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Banner buttonText={findingLocation ? "Loading..." : "Locate your coffee"} id="0" clickHandler={trackLocation}/>

      <CoffeeCards Stores={Stores}/>
    </div>
  )
}
